# randomization setup
RANDOM_SEED_GENERATOR = 123
RANDOM_SEED_SIMULATION = 456
RANDOM_SEED_MODEL = 789

# storage paths
STORAGE_ROOT_PATH = r'C:\Users\Pasi\Documents (offline)'
STORAGE_BASE_PATH_MASTER_DATA = STORAGE_ROOT_PATH + r'\Data Thesis'
STORAGE_BASE_PATH_SIMULATED_DATA = STORAGE_ROOT_PATH + r'\Data Thesis Simulated'
STORAGE_BASE_PATH_PY_GRAPHS = STORAGE_ROOT_PATH + r'\Data Thesis Simulated\pygraphs'
STORAGE_BASE_PATH_GRAPHVIZ_GRAPHS = STORAGE_ROOT_PATH + r'\Data Thesis Simulated\graphs'
STORAGE_BASE_PATH_PLOTS = STORAGE_ROOT_PATH + r'\Data Thesis Simulated\plots'

# runtime setup
CONF_GENERATE_MASTER_DATA = True
CONF_RUN_SIMULATION = True
CONF_GENERATE_SLICES_AND_GRAPHS = False

# initial master data generator setup
INIT_GEN_CUSTOMER_COUNT = 100
INIT_GEN_PRODUCT_COUNT = 100
INIT_GEN_SALESPERSON_COUNT = 10

# simulation setup
SIMULATION_END_TIME = 365 * 3 # = 1_095
SIMULATION_SPECIAL_EVENT_TIMES = [355, 720]

# graph generation & pruning
GRAPH_SLICER_WINDOW_DURATION = 2
GRAPH_PRUNING_MIN_CLUSTER_SIZE = 4

# output
VERBOSE_OUTPUT = False

